name: 个人数据更新
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 生成基本资料
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: github-basic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_timezone: Asia/Shanghai
          output_action: gist
          committer_gist: ${{ vars.GIST_ID }}
          config_padding: 0, 8
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
      - name: 生成使用语言等
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: github-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_timezone: Asia/Singapore
          output_action: gist
          committer_gist: ${{ vars.GIST_ID }}
          config_padding: 0, 8
          config_order: achievements, music, 16personalities
          base: ""
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_fortune: yes
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
      - name: 生成档案馆信息推特等
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: github-ysdag.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_timezone: Asia/Singapore
          output_action: gist
          committer_gist: ${{ vars.GIST_ID }}
          config_padding: 0, 8
          config_order: achievements, music, 16personalities
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://wiki.zorua.top/wiki/%E6%9C%89%E5%85%BD%E6%A1%A3%E6%A1%88%E9%A6%86:%E9%A6%96%E9%A1%B5
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_tweets: yes
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 1
          plugin_tweets_user: FoxZorua
      - name: 生成Steam和一堆杂项
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: github-steam.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          config_timezone: Asia/Singapore
          output_action: gist
          committer_gist: ${{ vars.GIST_ID }}
          config_padding: 0, 8
          config_order: achievements, music, 16personalities
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561199157941950"
